INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 1, 1);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 2, 1);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 3, 1);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 4, 1);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 5, 2);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 6, 2);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 7, 2);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 8, 2);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 9, 3);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 10, 3);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 11, 3);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 12, 3);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 13, 4);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 14, 4);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 15, 4);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 16, 4);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 17, 5);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 18, 5);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 19, 5);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 20, 5);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 21, 6);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 22, 6);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 23, 6);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 24, 6);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 25, 7);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 26, 7);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 27, 7);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 28, 7);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 29, 8);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 30, 8);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 31, 8);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 32, 8);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 33, 9);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 34, 9);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 35, 9);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 36, 9);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 37, 10);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 38, 10);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 39, 10);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 40, 10);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 41, 11);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 42, 11);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 43, 11);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 44, 11);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 45, 12);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 46, 12);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 47, 12);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 48, 12);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 49, 13);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 50, 13);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 51, 13);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 52, 13);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 53, 14);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 54, 14);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 55, 14);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 56, 14);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 57, 15);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 58, 15);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 59, 15);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 60, 15);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 61, 16);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 62, 16);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 63, 16);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 64, 16);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 65, 17);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 66, 17);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 67, 17);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 68, 17);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 69, 18);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 70, 18);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 71, 18);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 72, 18);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 73, 19);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 74, 19);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 75, 19);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 76, 19);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 77, 20);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 78, 20);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 79, 20);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 80, 20);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 81, 21);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 82, 21);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 83, 21);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 84, 21);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 85, 22);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 86, 22);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 87, 22);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 88, 22);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 89, 23);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 90, 23);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 91, 23);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 92, 23);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 93, 24);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 94, 24);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 95, 24);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 96, 24);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 97, 25);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 98, 25);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 99, 25);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 100, 25);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 101, 26);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 102, 26);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 103, 26);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 104, 26);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 105, 27);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 106, 27);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 107, 27);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 108, 27);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 109, 28);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 110, 28);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 111, 28);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 112, 28);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 113, 29);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 114, 29);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 115, 29);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 116, 29);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 117, 30);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 118, 30);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 119, 30);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 120, 30);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 121, 31);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 122, 31);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 123, 31);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 124, 31);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 125, 32);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 126, 32);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 127, 32);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 128, 32);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 129, 33);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 130, 33);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 131, 33);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 132, 33);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 133, 34);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 134, 34);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 135, 34);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 136, 34);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 137, 35);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 138, 35);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 139, 35);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 140, 35);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 141, 36);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 142, 36);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 143, 36);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 144, 36);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 145, 37);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 146, 37);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 147, 37);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 148, 37);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 149, 38);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 150, 38);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 151, 38);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 152, 38);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 153, 39);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 154, 39);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 155, 39);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 156, 39);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 157, 40);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 158, 40);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 159, 40);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 160, 40);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 161, 41);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 162, 41);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 163, 41);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 164, 41);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 165, 42);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 166, 42);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 167, 42);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 168, 42);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 169, 43);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 170, 43);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 171, 43);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 172, 43);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 173, 44);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 174, 44);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 175, 44);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 176, 44);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 177, 45);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 178, 45);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 179, 45);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 180, 45);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 181, 46);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 182, 46);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 183, 46);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 184, 46);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 185, 47);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 186, 47);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 187, 47);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 188, 47);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 189, 48);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 190, 48);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 191, 48);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 192, 48);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 193, 49);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 194, 49);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 195, 49);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 196, 49);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('normal', 197, 50);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('great ball', 198, 50);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('ultra ball', 199, 50);
INSERT INTO public.pokebola (nivel_de_forca, id, fk_treinador_id) VALUES('master ball', 200, 50);
