INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(1, 113, 225);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(2, 26, 126);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(3, 165, 79);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(4, 10, 171);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(5, 218, 205);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(6, 72, 135);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(7, 222, 204);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(8, 141, 182);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(9, 79, 16);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(10, 79, 96);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(11, 100, 240);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(12, 59, 9);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(13, 19, 58);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(14, 166, 196);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(15, 216, 58);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(16, 73, 83);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(17, 234, 88);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(18, 189, 107);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(19, 102, 64);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(20, 6, 144);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(21, 69, 159);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(22, 95, 17);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(23, 107, 232);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(24, 36, 251);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(25, 151, 174);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(26, 39, 195);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(27, 184, 130);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(28, 233, 76);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(29, 93, 243);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(30, 125, 120);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(31, 103, 149);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(32, 129, 170);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(33, 72, 143);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(34, 198, 139);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(35, 195, 165);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(36, 242, 84);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(37, 122, 11);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(38, 48, 117);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(39, 31, 200);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(40, 3, 95);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(41, 174, 189);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(42, 15, 33);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(43, 122, 92);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(44, 61, 221);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(45, 72, 171);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(46, 208, 202);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(47, 14, 22);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(48, 144, 144);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(49, 45, 145);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(50, 133, 116);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(51, 69, 139);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(52, 118, 115);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(53, 167, 208);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(54, 228, 113);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(55, 38, 170);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(56, 168, 179);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(57, 204, 242);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(58, 11, 25);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(59, 191, 95);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(60, 15, 160);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(61, 118, 40);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(62, 229, 1);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(63, 133, 29);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(64, 100, 75);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(65, 27, 240);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(66, 186, 129);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(67, 25, 131);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(68, 166, 118);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(69, 180, 186);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(70, 55, 167);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(71, 104, 150);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(72, 94, 33);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(73, 144, 160);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(74, 5, 160);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(75, 126, 199);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(76, 38, 37);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(77, 165, 55);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(78, 45, 227);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(79, 129, 114);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(80, 118, 143);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(81, 11, 139);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(82, 25, 124);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(83, 43, 239);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(84, 211, 61);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(85, 217, 198);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(86, 174, 238);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(87, 10, 30);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(88, 27, 66);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(89, 142, 206);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(90, 47, 98);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(91, 162, 38);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(92, 130, 124);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(93, 84, 127);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(94, 242, 190);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(95, 132, 223);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(96, 231, 83);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(97, 211, 178);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(98, 79, 41);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(99, 156, 205);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(100, 153, 32);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(101, 74, 140);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(102, 42, 64);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(103, 253, 178);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(104, 154, 24);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(105, 37, 113);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(106, 108, 177);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(107, 6, 95);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(108, 209, 92);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(109, 213, 246);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(110, 93, 35);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(111, 48, 133);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(112, 102, 147);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(113, 66, 150);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(114, 46, 102);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(115, 70, 142);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(116, 228, 185);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(117, 110, 69);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(118, 158, 167);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(119, 133, 105);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(120, 25, 87);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(121, 59, 238);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(122, 251, 153);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(123, 188, 129);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(124, 167, 208);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(125, 1, 110);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(126, 181, 198);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(127, 7, 123);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(128, 42, 23);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(129, 199, 139);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(130, 146, 149);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(131, 78, 161);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(132, 247, 147);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(133, 84, 25);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(134, 98, 241);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(135, 84, 172);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(136, 179, 161);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(137, 159, 29);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(138, 104, 250);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(139, 50, 115);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(140, 32, 186);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(141, 14, 214);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(142, 90, 234);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(143, 212, 140);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(144, 43, 224);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(145, 105, 11);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(146, 127, 188);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(147, 24, 8);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(148, 165, 138);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(149, 201, 104);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(150, 21, 152);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(151, 138, 183);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(152, 119, 228);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(153, 200, 72);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(154, 109, 91);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(155, 196, 188);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(156, 195, 236);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(157, 181, 114);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(158, 240, 192);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(159, 31, 66);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(160, 101, 12);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(161, 95, 203);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(162, 113, 73);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(163, 101, 133);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(164, 220, 178);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(165, 229, 76);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(166, 8, 98);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(167, 57, 59);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(168, 219, 87);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(169, 145, 59);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(170, 28, 138);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(171, 78, 69);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(172, 76, 49);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(173, 248, 87);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(174, 71, 224);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(175, 41, 170);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(176, 137, 94);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(177, 62, 72);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(178, 11, 114);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(179, 24, 163);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(180, 164, 40);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(181, 15, 74);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(182, 189, 93);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(183, 120, 28);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(184, 39, 198);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(185, 198, 29);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(186, 155, 143);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(187, 118, 118);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(188, 147, 5);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(189, 229, 217);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(190, 120, 213);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(191, 30, 210);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(192, 240, 61);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(193, 93, 199);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(194, 65, 71);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(195, 235, 224);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(196, 245, 53);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(197, 250, 85);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(198, 26, 176);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(199, 111, 163);
INSERT INTO treinador_batalha
(id_treinador_batalha, fk_treinador_id, fk_batalha_id)
VALUES(200, 182, 199);
