# Use postgres/example user/password credentials
version: '3.1'
services:
  postgresql:
    container_name: 'meucontainer'
    image: postgres
    restart: always
    volume:
      - ./data/postgres_pokemon.sql:/postgres_pokemon.sql
    environment:
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "seuemail@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1"
    ports:
      - "8090:80"
    depends_on:
      - postgresql
